version: "3"

services:
  php:
    container_name: php7.4
    build: ./docker/app
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
